[package]
name = "genetic-analysis-orders-benchmarking"
version = "2.1.0"
authors = ["agustinustheoo <agustinustheoo@gmail.com>"]
edition = '2021'
description = ''
homepage = ''
license = 'Unlicense'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
hex-literal = '0.3.4'
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

pallet-assets = { default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.18' }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }

genetic-analysts = { path = '../../genetic-analysts', default-features = false }
genetic-analyst-services = { path = '../../genetic-analyst-services', default-features = false }
genetic-analyst-qualifications = { path = '../../genetic-analyst-qualifications', default-features = false }
genetic-analysis = { path = '../../genetic-analysis', default-features = false }
genetic-analysis-orders = { path = '../../genetic-analysis-orders', default-features = false }
genetic-data = { path = '../../genetic-data', default-features = false }
user-profile = { path = '../../user-profile', default-features = false }

primitives-duration = { path = '../../../primitives/duration', default-features = false }
primitives-tracking-id = { path = '../../../primitives/tracking-id', default-features = false }
primitives-price-and-currency = { path = '../../../primitives/price-and-currency', default-features = false }
primitives-availability-status = { path = '../../../primitives/availability-status', default-features = false }

traits-genetic-analyst-services = { path = '../../genetic-analyst-services/traits', default-features = false }
traits-genetic-analysis = { path = '../../genetic-analysis/traits', default-features = false }
traits-genetic-analysis-orders = { path = '../../genetic-analysis-orders/traits', default-features = false }
traits-genetic-data = { path = '../../genetic-data/traits', default-features = false }
traits-user-profile = { path = '../../user-profile/traits', default-features = false }

[dev-dependencies]
serde = { default-features = false, version = "1.0.136" }

[features]
default = ['std']
std = [
    'codec/std',

    'sp-io/std',
    'sp-core/std',
    'sp-runtime/std',

    'frame-benchmarking/std',
    'frame-support/std',
    'frame-system/std',

	'pallet-assets/std',
	'pallet-timestamp/std',
	'pallet-balances/std',

    'genetic-analysts/std',
    'genetic-analyst-services/std',
	'genetic-analyst-qualifications/std',
	'genetic-analysis/std',
	'genetic-analysis-orders/std',
	'genetic-data/std',
    'user-profile/std',

    'primitives-duration/std',
    'primitives-tracking-id/std',
    'primitives-price-and-currency/std',
    'primitives-availability-status/std',

    'traits-genetic-analyst-services/std',
    'traits-genetic-analysis/std',
    'traits-genetic-analysis-orders/std',
    'traits-genetic-data/std',
    'traits-user-profile/std',
]
